#!/usr/bin/env bash

function compare {
  jade -P < $1.jade | cmp output/$1.html - &> /dev/null
}

if compare layout && compare layout_vanilla; then
  echo -e "\033[32m\n  PASSED!\033[0m\n  The Jade output matches the reference HTML.\n"
else
  echo -e "\033[31m\n  FAILED!\033[0m\n  The Jade output doesn't match the reference HTML.\n"
  exit 1
fi
